export type ErrorCode =
  | 'BAD_REQUEST'
  | 'UNAUTHORIZED'
  | 'NOT_FOUND'
  | 'CONFLICT'
  | 'SESSION_BUSY'
  | 'ACCOUNT_BUSY'
  | 'ACCOUNT_NOT_FOUND'
  | 'ACCOUNT_SWITCH_IN_PROGRESS'
  | 'CONCURRENCY_LIMIT'
  | 'AGY_NOT_INSTALLED'
  | 'AGY_NOT_AUTHENTICATED'
  | 'AGY_SPAWN_ERROR'
  | 'AGY_EXIT'
  | 'AGY_TIMEOUT'
  | 'AGY_ABORTED'
  | 'AGY_STALLED'
  | 'QUOTA_EXHAUSTED'
  | 'QUOTA_FETCH_FAILED'
  | 'ATTACHMENT_TOO_LARGE'
  | 'ATTACHMENT_TYPE_REJECTED'
  | 'PATH_OUTSIDE_WORKSPACE'
  | 'NOT_A_WORKSPACE'
  | 'INTERNAL';

export interface ApiErrorBody {
  code: ErrorCode;
  message: string;
  retryable: boolean;
  details?: Record<string, unknown>;
}

export interface ApiErrorResponse {
  error: ApiErrorBody;
}

export const ERROR_HTTP_STATUS: Record<ErrorCode, number> = {
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  NOT_FOUND: 404,
  CONFLICT: 409,
  SESSION_BUSY: 409,
  ACCOUNT_BUSY: 409,
  ACCOUNT_NOT_FOUND: 404,
  ACCOUNT_SWITCH_IN_PROGRESS: 423,
  CONCURRENCY_LIMIT: 429,
  AGY_NOT_INSTALLED: 503,
  AGY_NOT_AUTHENTICATED: 503,
  AGY_SPAWN_ERROR: 500,
  AGY_EXIT: 502,
  AGY_TIMEOUT: 504,
  AGY_ABORTED: 499,
  AGY_STALLED: 504,
  QUOTA_EXHAUSTED: 429,
  QUOTA_FETCH_FAILED: 502,
  ATTACHMENT_TOO_LARGE: 413,
  ATTACHMENT_TYPE_REJECTED: 415,
  PATH_OUTSIDE_WORKSPACE: 403,
  NOT_A_WORKSPACE: 400,
  INTERNAL: 500,
};
